package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;

import Clases.Ataque;
import Clases.Entrenador;
import Clases.Pokemon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author santi
 */
public class BatallaPokemon extends javax.swing.JFrame implements ActionListener {
    Entrenador entrenador1;
    Entrenador entrenador2;
    HashMap<String, String> imagenes;
    Pokemon pokemon1;
    Pokemon pokemon2;
    byte turno;
    /**
     * Creates new form BatallaPokemon
     */
    public BatallaPokemon(Entrenador entrenador1, Entrenador entrenador2, byte turno, Pokemon pokemon1, Pokemon pokemon2) {
        this.turno = turno;
        this.entrenador1 = entrenador1;
        this.entrenador2 = entrenador2;
        this.imagenes = entrenador1.getimagenes();
        this.pokemon1 = pokemon1;
        this.pokemon2 = pokemon2;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(816, 639));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(pokemon1.getNombre());
        jPanel2.add(jLabel1);
        jLabel1.setBounds(100, 90, 120, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(pokemon2.getNombre());
        jPanel2.add(jLabel2);
        jLabel2.setBounds(570, 90, 120, 30);

        jButton1.setText("<html>" + pokemon1.getAtaques().get(0).getNombreAtaque() + "<br>" + "daño:" +pokemon1.getAtaques().get(0).getPotencia() + "</html>");
        jPanel2.add(jButton1);
        jButton1.setBounds(30, 410, 130, 70);
        jButton1.addActionListener(this);
        jButton1.setActionCommand("0");

        jButton2.setText("<html>" + pokemon1.getAtaques().get(1).getNombreAtaque() + "<br>" +"daño:" + pokemon1.getAtaques().get(1).getPotencia() + "</html>");
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 500, 130, 70);
        jButton2.addActionListener(this);
        jButton2.setActionCommand("1");

        jButton3.setText("<html>" + pokemon1.getAtaques().get(2).getNombreAtaque() + "<br>" +"daño:" + pokemon1.getAtaques().get(2).getPotencia() + "</html>");
        jPanel2.add(jButton3);
        jButton3.setBounds(180, 410, 130, 70);
        jButton3.addActionListener(this);
        jButton3.setActionCommand("2");

        jButton4.setText("<html>" + pokemon1.getAtaques().get(3).getNombreAtaque() + "<br>" +"daño:" + pokemon1.getAtaques().get(3).getPotencia() + "</html>");
        jPanel2.add(jButton4);
        jButton4.setBounds(180, 500, 130, 70);
        jButton4.addActionListener(this);
        jButton4.setActionCommand("3");

        jButton5.setText("<html>" + pokemon2.getAtaques().get(0).getNombreAtaque() + "<br>" +"daño:" + pokemon2.getAtaques().get(0).getPotencia() + "</html>");
        jPanel2.add(jButton5);
        jButton5.setBounds(490, 410, 130, 70);
        jButton5.addActionListener(this);
        jButton5.setActionCommand("0");

        jButton6.setText("<html>" + pokemon2.getAtaques().get(1).getNombreAtaque() + "<br>" +"daño:" + pokemon2.getAtaques().get(1).getPotencia() + "</html>");
        jPanel2.add(jButton6);
        jButton6.setBounds(490, 500, 130, 70);
        jButton6.addActionListener(this);
        jButton6.setActionCommand("1");

        jButton7.setText("<html>" + pokemon2.getAtaques().get(2).getNombreAtaque() + "<br>" +"daño:" + pokemon2.getAtaques().get(2).getPotencia() + "</html>");
        jPanel2.add(jButton7);
        jButton7.setBounds(640, 410, 130, 70);
        jButton7.addActionListener(this);
        jButton7.setActionCommand("2");

        jButton8.setText("<html>" + pokemon2.getAtaques().get(3).getNombreAtaque() + "<br>" +"daño:" + pokemon2.getAtaques().get(3).getPotencia() + "</html>");
        jPanel2.add(jButton8);
        jButton8.setBounds(640, 500, 130, 70);
        jButton8.addActionListener(this);
        jButton8.setActionCommand("3");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenes.get(pokemon1.getNombre())))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(60,180,200,200);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText(Short.toString(pokemon2.getVida()));
        jPanel2.add(jLabel7);
        jLabel7.setBounds(570, 130, 120, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText(Short.toString(pokemon1.getVida()));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 130, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(imagenes.get(pokemon2.getNombre())))); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(530, 180, 200, 200);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Pikachu Fondo Resized.jpeg"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BatallaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BatallaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BatallaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BatallaPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration      
    
    public void Ocultarbotones() {
        if (turno == 1) {
            jButton1.setEnabled(true);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false); 
            jButton7.setEnabled(false);
            jButton8.setEnabled(false);
            mensajes("Es el turno de " + entrenador1.getNombre_entrenador() + " para atacar con " + pokemon1.getNombre() + "!");   
        } else {
            jButton1.setEnabled(false);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            jButton7.setEnabled(true);
            jButton8.setEnabled(true);
            mensajes("Es el turno de " + entrenador2.getNombre_entrenador() + " para atacar con " + pokemon2.getNombre() + "!");
        }
    }
    public void mensajes(String mensaje) {
        javax.swing.JOptionPane.showMessageDialog(this, mensaje, "Batalla Pokemon", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        int daño = 0;
            if (e.getSource()==jButton1  || e.getSource()==jButton2 || e.getSource()==jButton3 || e.getSource()==jButton4){
                int ataque1 = Integer.parseInt(e.getActionCommand());
                Ataque ataquePokemon1 = pokemon1.getAtaques().get(ataque1);
                daño = (ataquePokemon1.getPotencia()* ataquePokemon1.getPotencia())/ pokemon2.getDefensa();
                System.out.println(daño);
                if (pokemon1.getTipo() == pokemon2.getCounter()){
                    daño = daño + (int) (daño * 0.3);
                }
                pokemon2.setVida((short) (pokemon2.getVida() - daño));
                mensajes(entrenador1.getNombre_entrenador() + " ataca a " + pokemon2.getNombre() + " con " + ataquePokemon1.getNombreAtaque() + " y le hace " + daño + " de daño!");
                jLabel7.setText(Short.toString(pokemon2.getVida()));
                turno = (byte)(2);
                DecisionBatalla();
                
                
            }
            else if (e.getSource()==jButton5  || e.getSource()==jButton6 || e.getSource()==jButton7 || e.getSource()==jButton8){
                int ataque = Integer.parseInt(e.getActionCommand());
                Ataque ataque2 = pokemon2.getAtaques().get(ataque);
                daño = (ataque2.getPotencia()* ataque2.getPotencia())/ pokemon1.getDefensa();
                System.out.println(daño);
                if (pokemon2.getTipo() == pokemon1.getCounter()){
                    daño = daño + (int) (daño * 0.3);
                }
                pokemon1.setVida((short) (pokemon1.getVida() - daño));
                mensajes(entrenador2.getNombre_entrenador() + " ataca a " + pokemon1.getNombre() + " con " + ataque2.getNombreAtaque() + " y le hace " + daño + " de daño!");
                jLabel5.setText(Short.toString(pokemon1.getVida()));
                turno = (byte)(1);
                DecisionBatalla();
                
            }
        
        
    }
    public void DecisionBatalla(){
        if (pokemon1.getVida() <=0 || pokemon2.getVida() <=0){
            if (pokemon1.getVida() <=0){
                entrenador1.EliminarPokemon(pokemon1);
                mensajes("Ganador: " + entrenador2.getNombre_entrenador() + " con " + pokemon2.getNombre());
                SeleccionPokemon seleccionPokemon = new SeleccionPokemon(entrenador1, entrenador2);
                seleccionPokemon.EleccionesPokemon(entrenador1, entrenador2, pokemon2,2);
                this.setVisible(false);
                this.dispose();
            }else if (pokemon2.getVida() <=0){
                entrenador2.EliminarPokemon(pokemon2);
                mensajes("Ganador: " + entrenador1.getNombre_entrenador() + " con " + pokemon1.getNombre());
                SeleccionPokemon seleccionPokemon = new SeleccionPokemon(entrenador1, entrenador2);
                seleccionPokemon.EleccionesPokemon(entrenador1, entrenador2, pokemon1,1);
                this.setVisible(false);
                this.dispose();
            }
        }
        else{
            Ocultarbotones();
        }
    }
}
