/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Equipo Hogar
 */
package Vistas;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JOptionPane;

import Clases.Entrenador;

public class Entrenadores extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Entrenadores
     */
    public Entrenadores() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelDeEntrenadores = new javax.swing.JPanel();
        LabelEntrenadores = new javax.swing.JLabel();
        LabelEntrenador2 = new javax.swing.JLabel();
        TextFieldEntrenador2 = new javax.swing.JTextField();
        LabelEntrenador1 = new javax.swing.JLabel();
        TextFieldEntrenador1 = new javax.swing.JTextField();
        BotonContinuar = new javax.swing.JButton();
        LabelFondoEntrenadores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 28, 108));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(816, 639));

        PanelDeEntrenadores.setBackground(new java.awt.Color(153, 204, 255));
        PanelDeEntrenadores.setPreferredSize(new java.awt.Dimension(800, 600));
        PanelDeEntrenadores.setLayout(null);

        LabelEntrenadores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEntrenadores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Entrenadores Resized.png"))); // NOI18N
        PanelDeEntrenadores.add(LabelEntrenadores);
        LabelEntrenadores.setBounds(100, 20, 580, 160);

        LabelEntrenador2.setBackground(new java.awt.Color(255, 255, 255));
        LabelEntrenador2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEntrenador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEntrenador2.setText("Ingrese el nombre del entrenador 2");
        LabelEntrenador2.setOpaque(true);
        PanelDeEntrenadores.add(LabelEntrenador2);
        LabelEntrenador2.setBounds(20, 340, 360, 130);

        TextFieldEntrenador2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PanelDeEntrenadores.add(TextFieldEntrenador2);
        TextFieldEntrenador2.setBounds(420, 340, 360, 130);

        LabelEntrenador1.setBackground(new java.awt.Color(255, 255, 255));
        LabelEntrenador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelEntrenador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelEntrenador1.setText("Ingrese el nombre del entrenador 1");
        LabelEntrenador1.setOpaque(true);
        PanelDeEntrenadores.add(LabelEntrenador1);
        LabelEntrenador1.setBounds(20, 190, 360, 130);

        TextFieldEntrenador1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        PanelDeEntrenadores.add(TextFieldEntrenador1);
        TextFieldEntrenador1.setBounds(420, 190, 360, 130);

        BotonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Continuar Entrenadores Logo Resized.png"))); // NOI18N
        BotonContinuar.setBorderPainted(false);
        BotonContinuar.setContentAreaFilled(false);
        BotonContinuar.setPreferredSize(new java.awt.Dimension(123, 57));
        BotonContinuar.addActionListener(this);

        PanelDeEntrenadores.add(BotonContinuar);
        BotonContinuar.setBounds(160, 480, 480, 100);

        LabelFondoEntrenadores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Pikachu Fondo Resized.jpeg"))); // NOI18N
        PanelDeEntrenadores.add(LabelFondoEntrenadores);
        LabelFondoEntrenadores.setBounds(0, 0, 800, 600);

        getContentPane().add(PanelDeEntrenadores);
        PanelDeEntrenadores.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entrenadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonContinuar;
    private javax.swing.JLabel LabelEntrenador1;
    private javax.swing.JLabel LabelEntrenador2;
    private javax.swing.JLabel LabelEntrenadores;
    private javax.swing.JLabel LabelFondoEntrenadores;
    private javax.swing.JPanel PanelDeEntrenadores;
    private javax.swing.JTextField TextFieldEntrenador1;
    private javax.swing.JTextField TextFieldEntrenador2;
    // End of variables declaration                   
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == BotonContinuar) {
            TextFieldEntrenador1.getText();
            TextFieldEntrenador2.getText();
            Entrenador entrenador1 = new Entrenador(TextFieldEntrenador1.getText());
            Entrenador entrenador2 = new Entrenador(TextFieldEntrenador2.getText());
            entrenador1.elegirPokemonBatallaAutomatico();
            entrenador2.elegirPokemonBatallaAutomatico();
            entrenador1.agregraAtaquesPokemonesAutomatico();
            entrenador2.agregraAtaquesPokemonesAutomatico();
            JOptionPane.showMessageDialog(null, entrenador1.getNombre_entrenador() + entrenador1.getEquipo_entrenador());
            JOptionPane.showMessageDialog(null, entrenador2.getNombre_entrenador() + entrenador2.getEquipo_entrenador());
            this.setVisible(false);
            this.dispose();
            SeleccionPokemon seleccionPokemon = new SeleccionPokemon(entrenador1, entrenador2);
        }
    }
}
