/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Equipo Hogar
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class InicioPokemon extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form InicioPokemon
     */
    public InicioPokemon() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        PanelDeInicio = new javax.swing.JPanel();
        LabelLogo = new javax.swing.JLabel();
        BotonJugar = new javax.swing.JButton();
        LabelFondoInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(12, 28, 108));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(816, 639));

        PanelDeInicio.setLayout(null);

        LabelLogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Pokemon Java Logo.png"))); // NOI18N
        PanelDeInicio.add(LabelLogo);
        LabelLogo.setBounds(100, 50, 580, 160);

        BotonJugar.setBackground(new java.awt.Color(242, 242, 242));
        BotonJugar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotonJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Jugar Logo Resized.png"))); // NOI18N
        BotonJugar.setBorderPainted(false);
        BotonJugar.setContentAreaFilled(false);
        PanelDeInicio.add(BotonJugar);
        BotonJugar.setBounds(180, 380, 420, 120);
        BotonJugar.addActionListener(this);

        LabelFondoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logos/Pikachu Fondo Resized.jpeg"))); // NOI18N
        PanelDeInicio.add(LabelFondoInicio);
        LabelFondoInicio.setBounds(0, 0, 800, 600);

        getContentPane().add(PanelDeInicio);
        PanelDeInicio.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
                new InicioPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonJugar;
    private javax.swing.JLabel LabelFondoInicio;
    private javax.swing.JLabel LabelLogo;
    private javax.swing.JPanel PanelDeInicio;
    // End of variables declaration                   
    @Override
    public void actionPerformed(ActionEvent e) {
        this.dispose();
        this.setVisible(false);
        Entrenadores entrenadores = new Entrenadores();
    }
}
