/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Equipo Hogar
 */
package Vistas;
public class SeleccionPokemon extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionPokemon
     */
    public SeleccionPokemon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListEntrenador2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListEntrenador1 = new javax.swing.JList<>();
        LabelDeImagenEntrenador1 = new javax.swing.JLabel();
        LabelDeImagenEntrenador2 = new javax.swing.JLabel();
        LabelNombreEntrenador1 = new javax.swing.JLabel();
        LabelNombreEntrenador2 = new javax.swing.JLabel();
        BotonContinuarSeleccionPokemon = new javax.swing.JButton();
        LabelFondoSeleccionPokemon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        ListEntrenador2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pokemon 1 E2", "Pokemon 2 E2", "Pokemon 3 E2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        ListEntrenador2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(ListEntrenador2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 190, 170, 80);

        ListEntrenador1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Pokemon 1 E1", "Pokemon 2 E1", "Pokemon 3 E1" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(ListEntrenador1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(30, 190, 170, 80);

        LabelDeImagenEntrenador1.setBackground(new java.awt.Color(255, 255, 255));
        LabelDeImagenEntrenador1.setOpaque(true);
        jPanel1.add(LabelDeImagenEntrenador1);
        LabelDeImagenEntrenador1.setBounds(60, 70, 110, 110);

        LabelDeImagenEntrenador2.setBackground(new java.awt.Color(255, 255, 255));
        LabelDeImagenEntrenador2.setOpaque(true);
        jPanel1.add(LabelDeImagenEntrenador2);
        LabelDeImagenEntrenador2.setBounds(330, 70, 110, 110);

        LabelNombreEntrenador1.setBackground(new java.awt.Color(255, 255, 255));
        LabelNombreEntrenador1.setText("Nombre Entrenador 1");
        LabelNombreEntrenador1.setOpaque(true);
        jPanel1.add(LabelNombreEntrenador1);
        LabelNombreEntrenador1.setBounds(30, 20, 170, 40);

        LabelNombreEntrenador2.setBackground(new java.awt.Color(255, 255, 255));
        LabelNombreEntrenador2.setText("Nombre Entrenador 2");
        LabelNombreEntrenador2.setOpaque(true);
        jPanel1.add(LabelNombreEntrenador2);
        LabelNombreEntrenador2.setBounds(300, 20, 170, 40);

        BotonContinuarSeleccionPokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Continuar Entrenadores Logo Resized.png"))); // NOI18N
        BotonContinuarSeleccionPokemon.setBorderPainted(false);
        BotonContinuarSeleccionPokemon.setContentAreaFilled(false);
        BotonContinuarSeleccionPokemon.setPreferredSize(new java.awt.Dimension(123, 57));
        BotonContinuarSeleccionPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonContinuarSeleccionPokemonActionPerformed(evt);
            }
        });
        jPanel1.add(BotonContinuarSeleccionPokemon);
        BotonContinuarSeleccionPokemon.setBounds(140, 300, 200, 57);

        LabelFondoSeleccionPokemon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pikachu Fondo Resized.jpeg"))); // NOI18N
        jPanel1.add(LabelFondoSeleccionPokemon);
        LabelFondoSeleccionPokemon.setBounds(0, 0, 500, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void BotonContinuarSeleccionPokemonActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BotonContinuarSeleccionPokemon;
    private javax.swing.JLabel LabelDeImagenEntrenador1;
    private javax.swing.JLabel LabelDeImagenEntrenador2;
    private javax.swing.JLabel LabelFondoSeleccionPokemon;
    private javax.swing.JLabel LabelNombreEntrenador1;
    private javax.swing.JLabel LabelNombreEntrenador2;
    private javax.swing.JList<String> ListEntrenador1;
    private javax.swing.JList<String> ListEntrenador2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration                   
}
